# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarioreward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=100)),
                ('s_money', models.BigIntegerField()),
                ('s_reward', models.CharField(max_length=50)),
                ('r_delivery', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'scenarioreward',
            },
        ),
        migrations.CreateModel(
            name='Sinariodatado',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_jang', models.CharField(max_length=100)),
                ('s_title', models.CharField(max_length=50)),
                ('s_content', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('s_spon_money', models.BigIntegerField()),
                ('s_spon_date', models.DateField()),
                ('s_regdate', models.DateField(auto_now_add=True)),
                ('s_bank', models.CharField(max_length=30)),
                ('s_bank_name', models.CharField(max_length=20)),
                ('s_account', models.CharField(max_length=50)),
                ('s_amount', models.BigIntegerField(default=0)),
                ('s_deposit_money', models.BigIntegerField(default=0)),
                ('u_introduce', models.TextField()),
                ('s_purpose', models.TextField()),
                ('s_core', models.TextField()),
                ('s_plan', models.TextField()),
                ('sw_phone', models.TextField(default=False)),
                ('sw_email', models.TextField(default=False)),
            ],
            options={
                'db_table': 'sinariodatado',
            },
        ),
    ]
