# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_sinariodatado_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioreward',
            name='s_reward',
            field=models.CharField(max_length=120),
        ),
    ]
