# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterdatado',
            name='t_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theaterdatado',
            name='t_lng',
            field=models.CharField(max_length=100),
        ),
    ]
