# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_title', models.CharField(max_length=70)),
                ('m_title_id', models.CharField(blank=True, max_length=70, null=True)),
                ('m_genre', models.CharField(blank=True, max_length=50, null=True)),
                ('m_runtime', models.CharField(blank=True, max_length=30, null=True)),
                ('m_opendate', models.CharField(blank=True, max_length=30, null=True)),
                ('m_class', models.CharField(blank=True, max_length=30, null=True)),
                ('m_class_id', models.CharField(blank=True, max_length=30, null=True)),
                ('m_director', models.CharField(blank=True, max_length=70, null=True)),
                ('m_actor', models.CharField(blank=True, max_length=300, null=True)),
                ('m_scenario', models.CharField(blank=True, max_length=3000, null=True)),
                ('m_image_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
