# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movietime',
            fields=[
                ('mt_id', models.AutoField(primary_key=True, serialize=False)),
                ('mt_day', models.DateField(blank=True, null=True)),
                ('mt_time', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'movietime',
            },
        ),
        migrations.CreateModel(
            name='Screentheater',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'screentheater',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_reserved', models.BooleanField(default=False)),
                ('mt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Movietime')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
    ]
