# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdatado',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_idtext', models.CharField(max_length=15, unique=True)),
                ('u_password', models.CharField(max_length=128)),
                ('u_name', models.CharField(max_length=15)),
                ('u_birth', models.CharField(max_length=10)),
                ('u_birth1', models.CharField(max_length=10)),
                ('u_birth2', models.CharField(max_length=10)),
                ('u_phone', models.CharField(max_length=20)),
                ('is_writered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('salt', models.CharField(blank=True, max_length=10, verbose_name='Salt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'userdatado',
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.userdatado',),
        ),
    ]
