# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-26 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatado',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
