# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-26 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdatado_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatado',
            name='address',
        ),
    ]
