# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundingdatado',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_amount', models.BigIntegerField(default=0)),
                ('f_created_at', models.DateTimeField(auto_now_add=True)),
                ('f_cardnum', models.CharField(max_length=50)),
                ('f_vaildity', models.CharField(max_length=20)),
                ('f_cardpass', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'fundingdatado',
            },
        ),
    ]
