# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0002_fundingdatado_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingdatado',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FundingStatistic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('funding.fundingdatado',),
        ),
    ]
