# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-26 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_auto_20191125_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingdatado',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
